### ISSUE TITLE
`kerl status` shows always the same current active installation

### ISSUE THREAD

**Issue by jfacorro** [belltoy/kerl-fish#2]

**Comment by jfacorro** [comment]
Actually this only happens if the `activate` for a specific installation is run on `config.fish`. This is specific how `fish` works, looks like what is executed in the `config.fish` script is run under a specific special context, although I couldn't find an explanation in the reference.

**Comment by jfacorro** [comment]
This fixes the issue:

```
## Activate Erlang OTP 18.0
if status --is-interactive
    . ~/dev/erlang/18.0/activate
end
```

**Comment by belltoy** [comment]
Hi, @jfacorro

I was on a vacation trip recently, and I'm sorry for missing your issue and RP.

This repo is not ready, and it's long time no update. There is a [RP](https://github.com/yrashk/kerl/pull/91) which add fish shell support for the repo [yrashk/kerl](https://github.com/yrashk/kerl). Maybe that is the better option for the fish shell.

Thanks a lot anyway.
